filter: { filter: [OnlyUniqueDocs], recursive: True }
wrappers: ExcludeEmptyDirs
docs:
  filter:
      - MessageWithOtherDocument
      - Not:
          - ByExtension: .zip
.sysinfo:
  producer: SysInfo
music:
  filter: MessageWithMusic
reactions:
  filter: MessageWithReactions
zips:
  filter: MessageWithZip
voice-and-round:
  filter:
    Union: [MessageWithKruzhochek, MessageWithVoice]
video:
  filter: MessageWithVideoFile
images:
  filter:
    Union: [MessageWithDocumentImage, MessageWithCompressedPhoto]
stickers:
  filter:
    Union: [MessageWithAnimated, MessageWithSticker]
messages:
  filter: MessageWithText
  treat_as: MessageWithText
all:
  filter: All
by-forward: 
  filter: MessageForwarded
  producer: ByForward  
music-by-performer:
  filter: MessageWithMusic
  producer: ByPerformer
forwarded-video:
  filter:
    And: [MessageForwarded, MessageWithVideo]
by-reactions: 
  producer: ByReactions      
likes: 
  filter: 
    - ByReaction: 
        reaction: 👍
top-likes: 
  filter: 
    - ByReaction: 
        reaction: 👍
        minimum: 5
unpacked:
  filter: MessageWithZip
  producer: 
    UnpackedZip: 
      skip_folder_if_single_subfolder: True
      hide_sources: False
  # it's recommended to use cache with UnpackedZip. otherwise it is slow
  cache: 
    type: memory
    block_size: 256KB
    capacity: 300MB
