mount_dir: /home/horn/mnt/tgmount1

client:
  session: tgfs
  api_id: 123
  api_hash: deadbeed121212121

message_sources:
  # separate requests for music
  ru2chmu-music:
    entity: ru2chmu
    updates: False
    filter: InputMessagesFilterMusic
    limit: 1000

  # and for documents
  ru2chmu-documents:
    entity: ru2chmu
    updates: False
    filter: InputMessagesFilterDocument
    limit: 1000

  friends:
    entity: -388004022
    limit: 1000
    
caches:
  memory1:
    type: memory
    capacity: 300MB
    block_size: 128KB

root:
  filter: { filter: OnlyUniqueDocs, recursive: True }
  muzach:
    music:
      source: ru2chmu-music
      # the directory will contain music
      filter: MessageWithMusic
    zips:
      source: ru2chmu-documents
      # will select zip files
      filter: MessageWithZip
      
      producer: UnpackedZip
      # using cache speeds up reading from the archives
      cache: memory1

  friends:
    source: {source: friends, recursive: True}
    music-by-senders:
      producer:
        # this producer creates a separate directory for every sender in the entity
        BySender:
          dir_structure:
            # these directories will only contain 
            filter: MessageWithMusic
    liked-music:
      # this directory will be containing all music with thumb up reaction
      filter: 
        And: 
          - MessageWithMusic
          - ByReaction: 
              reaction: 👍
    images:
      filter: 
        Union: [MessageWithCompressedPhoto, MessageWithDocumentImage]